- hosts: all
  tasks:
  - name: Clone GitHub repository to local
    ansible.builtin.git:
      repo: 'https://github.com/akoshiro/test.git'
      dest: /win
      version: main

  - name: copy /sbt_smg_work to managed nodes
    ansible.windows.win_copy:
      src: /win
      dest: /sbt_smg_work/test/
